- name: Configure webservers
  hosts: tag_webserver
  gather_facts: no
  become: yes
  roles:
    - role: common
    - role: webserver

- name: Deploy web applications
  hosts: tag_webserver
  gather_facts: no
  become: yes
  tags: deploy
  tasks:
    - name: Deploying BigBro SPA
      include_role:
        name: website
      vars:
        application_name: bigbro-spa
        application_domain_name: prototype.lab.crazyinventor.net
        application_domain_name_append_www: false
    - name: Deploying DavidSchneider.info website
      include_role:
        name: website
      vars:
        application_name: dsinfo
        application_domain_name: davidschneider.info
