- name: Configure webservers
  hosts: tag_webserver
  gather_facts: no
  become: yes
  tags: system
  roles:
    - role: common
    - role: webserver

- name: Deploy example
  tags: app
  vars:
    application: example
  import_playbook: webapp.yml

- name: Deploy bigbro-ui
  tags: app
  vars:
    application: bigbro-ui
  import_playbook: webapp.yml

- name: Deploy bigbro-api
  tags: app
  vars:
    application: bigbro-api
  import_playbook: webapp.yml

- name: Deploy dsinfo
  tags: app
  vars:
    application: dsinfo
  import_playbook: webapp.yml
