- name: Prepare webservers
  hosts: tag_webserver
  gather_facts: no
  become: yes
  tags: provision
  roles:
    - role: common
    - role: webserver

- name: Deploy web applications
  hosts: tag_webserver
  gather_facts: no
  become: yes
  tags:
    - deploy
    - provision
  roles:
    - role: spa
