- name: "Write Nginx site config for API"
  template:
    src: website.conf
    dest: "/etc/nginx/sites-available/{{ application_name }}.conf"
    mode: '0644'
    owner: root
    group: root
  register: nginx_site_conf

- name: check if ssl certs exists
  stat:
    path: "/etc/letsencrypt/live/{{ application_domain_name }}"
  register: api_ssl_conf_exists

- name: Run LetsEncrypt
  command: certbot --nginx -d {{ application_domain_name }} --expand --non-interactive --agree-tos -m d4vid81@gmail.com certonly
  when: api_ssl_conf_exists.stat.exists == false

- name: Enable Nginx site config for API
  file:
    src: "/etc/nginx/sites-available/{{ application_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ application_name }}"
    mode: '0644'
    owner: root
    group: root
    state: link

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
  when: nginx_site_conf.changed == true
