- name: Initialize the deployment
  deploy_helper:
    path: "{{ application_root_directory }}"

- name: Connect to gcloud console
  shell: gcloud auth activate-service-account --key-file=/root/gc-storage.json
  check_mode: false

- name: Check list of latest archived artifact
  shell: gsutil ls -l gs://crazyinventor-build-artifacts/{{ application_name }} | sort -k 2 -r | grep "master-" | awk '{print $NF}'
  register: gsutil_list
  check_mode: false

- name: "Download archived artifact {{ gsutil_list.stdout_lines[0] }}"
  shell: "gsutil cp {{ gsutil_list.stdout_lines[0] }} {{ application_root_directory }}/tmp/latest.tar.gz"

- name: Extract archived artifact
  unarchive:
    src: "{{ application_root_directory }}/tmp/latest.tar.gz"
    dest: "{{ application_root_directory }}/tmp"
    remote_src: yes
  when: not ansible_check_mode

- name: Copy artifact to new_release_path
  command: "mv {{ application_root_directory }}/tmp/dist {{ deploy_helper.new_release_path }}"
  when: not ansible_check_mode

- name: Remove archived artifact
  file:
    path: "{{ application_root_directory }}/latest.tar.gz"
    state: absent
  when: not ansible_check_mode

- name: Finalize the deployment
  deploy_helper:
    path: "{{ application_root_directory }}"
    release: '{{ deploy_helper.new_release }}'
    state: finalize
    keep_releases: 10
