- name: create cron job
  cron:
    name: "{{ item.key }}"
    month: "{{ item.value.cron_task_month }}"
    day: "{{ item.value.cron_task_day }}"
    weekday: "{{ item.value.cron_task_weekday }}"
    minute: "{{ item.value.cron_task_minute }}"
    hour: "{{ item.value.cron_task_hour }}"
    user: "{{ item.value.cron_task_user }}"
    job: "{{ item.value.cron_task_job }}"
    state: "{{ item.value.cron_task_state }}"
  with_dict: "{{ application_cronjobs }}"
