- name: Initialize the deployment
  deploy_helper:
    path: /srv/spa

- name: Connect to gcloud console
  shell: gcloud auth activate-service-account --key-file=/root/gc-storage.json

- name: Check list of latest archived artifact
  shell: gsutil ls -l gs://crazyinventor-build-artifacts/bigbro-spa | sort -k 2 -r | awk '{print $NF}'
  register: gsutil_list

- name: Download archived artifact
  shell: "gsutil cp {{ gsutil_list.stdout_lines[1] }} /srv/spa/latest.tar.gz"

- name: Extract archived artifact
  shell: "tar -xvf latest.tar.gz"
  args:
    chdir: /srv/spa
  register: artifact_extract

- name: Move artifact to new_release_path
  command: "mv /srv/spa/dist {{ deploy_helper.new_release_path }}"

- name: Remove archived artifact
  shell: "rm /srv/spa/latest.tar.gz"

- name: Finalize the deployment
  deploy_helper:
    path: /srv/spa
    release: '{{ deploy_helper.new_release }}'
    state: finalize
    keep_releases: 10
