- name: Check application directory
  file:
    path: /srv/spa
    state: directory
    mode: '0755'
    owner: www-data
    group: www-data
    recurse: yes

- include_tasks: deploy.yml

- name: check if nginx site config exists
  stat:
    path: /etc/nginx/sites-enabled/spa
  register: nginx_spa_conf

- include_tasks: website.yml
  when: nginx_spa_conf.stat.exists == false
