- name: Install required packages for PHP
  when: not ansible_check_mode
  apt:
    pkg:
    - php7.2-common
    - php7.2-fpm
    - php7.2-cli
    - php7.2-json
    - php7.2-mbstring
    - php7.2-mysql
    - php7.2-opcache
    - php7.2-sqlite3
    - php7.2-readline
    - php-pear

- name: create php fpm settings
  file:
    path: /etc/php/7.2/fpm/conf.d/90-centerverse.ini
    owner: root
    group: root
    mode: '0644'
    state: touch
  register: php_ini
  when: not ansible_check_mode
  changed_when: php_ini.diff.before.state == "absent"

- name: update php fpm settings
  lineinfile:
    path: /etc/php/7.2/fpm/conf.d/90-centerverse.ini
    regexp: "cgi.fix_pathinfo="
    line: "cgi.fix_pathinfo=0"
    state: present
  when: php_ini.changed == true
  notify: restart php
